apiVersion: v1
kind: Service
metadata:
  name: travelmemory-backend
spec:
  selector:
    app: travelmemory-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
