apiVersion: v1
kind: Service
metadata:
  name: travelmemory-frontend
spec:
  selector:
    app: travelmemory-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
